---
- name: install package
  hosts: localhost
  become: yes

  tasks:
    - name: install packages
      yum:
        name: yum-utils
        state: present

    - name: add docker-repo
      command:
        cmd: "/bin/bash -c 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'"

    - name: install docker packages
      yum:
        name: "{{ docker_packages }}"
        state: present
      vars:
        docker_packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: service restart
      service:
        name: docker
        enabled: yes
        state: restarted

    - name: check docker version
      command:
        cmd: /bin/bash -c 'docker version'

    - name: Swap Disabled
      command:
        cmd: /bin/bash -c 'swapoff -a && sed -i '/swap/s/^/#/' /etc/fstab'

    - name: Letting iptables see bridged traffic
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        line: net.bridge.bridge-nf-call-ip6tables = 1\nnet.bridge.bridge-nf-call-iptables = 1

    - name: Disable firewall
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Set SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: k8s repo add
      yum_repository:
        name: Kubernetes
        description: Kubernetes Repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude: kubelet kubeadm kubectl

    - name: install k8s packages
      yum:
        disable_excludes: Kubernetes
        name: "{{ k8s_packages }}"
        state: present
      vars:
        k8s_packages:
        - kubelet
        - kubeadm
        - kubectl

    - name: restart & enable kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
