apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fs-echo-ip-dev
  name: fs-echo-ip-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs-echo-ip-dev
  template:
    metadata:
      labels:
        app: fs-echo-ip-dev
    spec:
      containers:
      - image: 10.25.240.21:8443/echo-ip
        name: fs-echo-ip-dev
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fs-echo-ip-dev
  name: fs-echo-ip-dev-svc
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: fs-echo-ip-dev
  type: LoadBalancer
