apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.25.240.21
    path: /nfs_shared/prometheus/alertmanager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
